// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmtaJ7qjTWoWUZyHJe3EAkDPClfP0kci8',
    appId: '1:817573489333:web:5cbd4f222fd15d2a15acfc',
    messagingSenderId: '817573489333',
    projectId: 'newproject-baf04',
    authDomain: 'newproject-baf04.firebaseapp.com',
    storageBucket: 'newproject-baf04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMkADm1KVm7lz1Ph3Bpurn8dLiz_BcP04',
    appId: '1:817573489333:android:31b415b377696e1315acfc',
    messagingSenderId: '817573489333',
    projectId: 'newproject-baf04',
    storageBucket: 'newproject-baf04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvoB_OfscNwBuKRdRI9R0qemJytMlZu-A',
    appId: '1:817573489333:ios:5f50e6db56698aed15acfc',
    messagingSenderId: '817573489333',
    projectId: 'newproject-baf04',
    storageBucket: 'newproject-baf04.appspot.com',
    iosBundleId: 'com.example.seawind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvoB_OfscNwBuKRdRI9R0qemJytMlZu-A',
    appId: '1:817573489333:ios:5f50e6db56698aed15acfc',
    messagingSenderId: '817573489333',
    projectId: 'newproject-baf04',
    storageBucket: 'newproject-baf04.appspot.com',
    iosBundleId: 'com.example.seawind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmtaJ7qjTWoWUZyHJe3EAkDPClfP0kci8',
    appId: '1:817573489333:web:7a3f98a136a94a2415acfc',
    messagingSenderId: '817573489333',
    projectId: 'newproject-baf04',
    authDomain: 'newproject-baf04.firebaseapp.com',
    storageBucket: 'newproject-baf04.appspot.com',
  );
}
